### ISSUE TITLE
The experiment skill of BG4-ChIP-seq

### ISSUE THREAD

**Issue by huangzh0818** [sblab-bioinformatics/dna-secondary-struct-chrom-lands#2]
Hi Dario ! My lab have some interest for the BG4-ChIP-seq, and I tried some times for BG4-ChIP-qPCR in HaCaT cell line. But I got the enrichment of positive control and negative control in BG4-IP samples. The BG4 antibody is purchased from Absolute antibody company (http://absoluteantibody.com/ababs/ab00174-1-1-anti-dnarna-g-quadruplex-and-related-small-molecules-bg4/). Could you give me some addvise or the detail protocol for BG4-ChIP-qPCR? Thank you! My e-mail is huangzh0818@hotmail.com.

**Comment by dariober** [comment]
Hi- I suggest you contact Robert, the first author of our paper, at robert.hansel-hertsch"at"cruk.cam.ac.uk. He should be able to advise on the experimental protocol. As bioinformatician I cannot help you much in this respect!

Good luck!
Dario

**Comment by huangzh0818** [comment]
Thank you for replay! I will email the first author in the soon!Thank you!

Zenghui Huang

On 22 Nov 2017, at 9:56 PM, Dario Beraldi <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2<https://github.com/sblab-bioinformatics/dna-secondary-struct-chrom-lands/issues/2>.

**Comment by huangzh0818** [comment]
Hi, Dario! I am sorry, I can not get contact with the first author even can not open the URL you given! Please give me the email of the first author! Thank you!
Zenghui

发件人: Dario Beraldi<mailto:notifications@github.com>
发送时间: 2017年11月22日 21:56
收件人: sblab-bioinformatics/dna-secondary-struct-chrom-lands<mailto:dna-secondary-struct-chrom-lands@noreply.github.com>
抄送: Zenghui Huang<mailto:huangzh0818@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [sblab-bioinformatics/dna-secondary-struct-chrom-lands] The experiment skill of BG4-ChIP-seq (#2)


Closed #2<https://github.com/sblab-bioinformatics/dna-secondary-struct-chrom-lands/issues/2>.

―

**Comment by dariober** [comment]
Hi - Try this email address robert.hansel-hertsch@cruk.cam.ac.uk

Dario
